name: Mirror to AstralServer/SharedAPI

on:
  push:
    branches:
      - "main"

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config user.name "Traqueur_"
          git config user.email "%traqueur.dev@gmail.com"

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run Python script to mirror branch
        env:
          SOURCE_BRANCH: "main"
          TARGET_REPO: "AstralServer/SharedAPI"
          MIRROR_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          python mirror_push.py